language: python

python:
  - '3.6'
  - '3.7'
  - '3.8'

env:
  global:
    - AWS_DEFAULT_REGION=ap-southeast-2
    - DOCKER_REPO=samjarrett/cfn-sync
    - secure: "uZazcGVJFIUvzadFYeRExZOtFgknGniqz96SDQMD6sI2EcWN5diJpZCfSELJtKoSbLYt/04oN6tqW9YauiUq2Jsog4evBn7G7I1NPEW+GGY//R05SKPztgipenDmoTIKdFvAzZrzmRX4nXfleBqlgxa1MOsBg+LWsyxiLxo2nJe77RM289a7GjYEvoopLywdiRBGAtX5MebjmI8PLeQP+3h8luBSlOOg96vAVcv4/qF5ktNnK3NU/oGh6pfUUDYY7rFBU1FWf2EyoD+mDXk+thog/YUNXiTnjhJdeQ+0DpiFLU/J2YcNOjadkNuOd9bxFmwrQoWjXHkDKWCrYpWl3xuR+A3/GRNbgATyczgtk+05H1ooXLrvNyFXtgwhRnrgAR2rusMqzvcYUP84A+JnwlSeMCMPgOVKluUUrL67MCkmSh+Lm46XujMXUClwaxz5u+U1ksFFhUUFsy2nb78CVCyS1BA/NIxFd3zvvJ4L33MbQdkMhdRJ4xGdzU6XNb+mPaaDqkjgFMPe7F8zcwOjpGPWVdyTjc7eQRvSvMvIlBU8kN2stz3PLIUEuDOvMxdxD38OnG2i4o/fM1GODIK1T1itHqSdkydYBgaHo6OjaWtc9cH+rLZPuIOe8XOV1yHemT2LkmbnvtMpRpizA2Zlf3rvNtExu1snd2GZCTTMLUU="
    - secure: "S24HTcEJPO1xKBCLdFDvG+kUpU3KGdQ1khjX7QUlGTNVX/HMUH8FaC/yJXgXDpKHwbrqE1AAWYACeB+Jp5se8uDXnJJQxUjhj3E/C62ExB2WVERh62ZfTP97bb3WkUSTePtmd9rENX7roJmCWERXsSa/fsaGcqgzRm/hg1Nnc6LELEmEb0xP7dcHd78hc8SOZjvPO8C2QiKA4qxxd3xN1PqxSYwFhhI70bgGuCmCIFrnzPs+3yKOZ7IBBoqwvb2YEPoSSi3jQi5/9UhWdeE6b08SdKXwpG4lPmtevWwy0xVY/FzYT2Oj+sCkrDpFZaHhFZXGvccff1diW476z8Rh8T2KuLrm+CrmsiQUKlKiA8hKRWnuZ6+qxo3ci14qeVvWevah6WBCQeHFPiyg6rQP9uA14sZqg8KlTELcHqBphpjsPfBsvjC6ujFVmXrSgmGYU/ym52KYtuhd3wDYdxFkVMi8/nKRAyONv6chmAE7BvD7/7cUNWE1fI5g2ofWRh+CYKsoR5wchNw1e6Bu1T/aFoHUPrsKUN/NxbKbExUz1tfxu5zKZjH8tDL8to7u6NADsPUqBZaylEz6BirMgFGRJcgHj1UR5Fxs6Oh7LEYqMdyAWpzUsXBVgHoPgmK+lTQH6L5D/I1+M99tMLJ6K9NjLmPPArBmQ4Tv4vuBD6cfj0g="

cache:
  - pip
before_install:
  - pip install -U pip setuptools
  - pip install -r dev-requirements.txt

script:
  - pytest --cov stackup
  - pylint cfn_sync tests setup.py
  - black -c cfn_sync tests setup.py
  - mypy cfn_sync

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: oSY9w7r6tCz+NgNA5obfO4Q3fUkkKAwIXv1ggbkf/m0ZQ+Qgn0nBSfig9od3qqIe08T57ip2/ngojm26TpFfKNwspljq6/IefEduzIEVSsmWyxhjnmnsOhNvaufM/Mwt2ERUgKr0poYZjCiI3SWS+Rs/ZB35dH9U+ZGyJ3P+tlTnzLU9vYid0SLbMjRy1RqqTdisJ/ht0fq6xkdmrDQ3ohBaWZL1FzJ2pG99Gz47MitBUXxt5M+F1L/i5EWSWPlMGitA0vgcKyCIdo+Xou/q1DJ2/gONmI5lNSL4cQci+dbSKNbxuoovQefcJY0+4qhs3n2iVvPMrWdVLdciRxHmgOP5CE62gZcH4QMSD6NLlUP9LnGCp9zFDv9UTT7W3xW/OAOvOa1ajkoWRePOfZAzRBtOSxxMmCgSd9AH9HWOtYU8vV/K6ojRnfhKnT/HTF7Bwbw5glWbxl+26BA96okThYVZGkXf75oAmLgLMf4+AJC9L/BAnAlIQrN2b/l76G9/Y78wtDyPAJaCecxRRejsfeNITsN6sHVkE1wckhzMUsbhSOz5P4LY+vO6ncwEgGBtY9Iwqh6GHHuDyUQ1qYpLhMtv2q2YREeBARuJ8wbypFILqopdz1voWXQkH2UmmxW4n/YCw8WyY+GzmP4lxb1/YVDX6xg/wsGue3r+NxeDFuo=
  on:
    tags: true
    python: 3.8

after_deploy:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - docker build --build-arg CFN_SYNC_VERSION=${TRAVIS_TAG} --tag "${DOCKER_REPO}:${TRAVIS_TAG}" .
  - docker push "${DOCKER_REPO}:${TRAVIS_TAG}"
  - docker tag "${DOCKER_REPO}:${TRAVIS_TAG}" "${DOCKER_REPO}:latest"
  - docker push "${DOCKER_REPO}:latest"
